/* eslint-disable */
// Generated by scripts/gen-translations.mjs — do not edit.

import en_common from './en/common.json';
import en_consent from './en/consent.json';
import en_credits from './en/credits.json';
import en_errorBoundary from './en/errorBoundary.json';
import en_errors from './en/errors.json';
import en_gift from './en/gift.json';
import en_legal from './en/legal.json';
import en_nav from './en/nav.json';
import en_notifications from './en/notifications.json';
import en_onboarding from './en/onboarding.json';
import en_paywall from './en/paywall.json';
import en_preview from './en/preview.json';
import en_report from './en/report.json';
import en_settings from './en/settings.json';
import en_toast from './en/toast.json';
import en_ui from './en/ui.json';
import tr_common from './tr/common.json';
import tr_consent from './tr/consent.json';
import tr_credits from './tr/credits.json';
import tr_errorBoundary from './tr/errorBoundary.json';
import tr_errors from './tr/errors.json';
import tr_gift from './tr/gift.json';
import tr_legal from './tr/legal.json';
import tr_nav from './tr/nav.json';
import tr_notifications from './tr/notifications.json';
import tr_onboarding from './tr/onboarding.json';
import tr_paywall from './tr/paywall.json';
import tr_preview from './tr/preview.json';
import tr_report from './tr/report.json';
import tr_settings from './tr/settings.json';
import tr_toast from './tr/toast.json';
import tr_ui from './tr/ui.json';

export const resources = {
  'en': { translation: { "common": en_common, "consent": en_consent, "credits": en_credits, "errorBoundary": en_errorBoundary, "errors": en_errors, "gift": en_gift, "legal": en_legal, "nav": en_nav, "notifications": en_notifications, "onboarding": en_onboarding, "paywall": en_paywall, "preview": en_preview, "report": en_report, "settings": en_settings, "toast": en_toast, "ui": en_ui } },
  'tr': { translation: { "common": tr_common, "consent": tr_consent, "credits": tr_credits, "errorBoundary": tr_errorBoundary, "errors": tr_errors, "gift": tr_gift, "legal": tr_legal, "nav": tr_nav, "notifications": tr_notifications, "onboarding": tr_onboarding, "paywall": tr_paywall, "preview": tr_preview, "report": tr_report, "settings": tr_settings, "toast": tr_toast, "ui": tr_ui } },
} as const;

export type EnTranslation = (typeof resources)['en']['translation'];
