/* eslint-disable */
// Generated by scripts/gen-translations.mjs — do not edit.

import en_errorBoundary from './en/errorBoundary.json';
import en_nav from './en/nav.json';
import tr_errorBoundary from './tr/errorBoundary.json';
import tr_nav from './tr/nav.json';

export const resources = {
  'en': { translation: { "errorBoundary": en_errorBoundary, "nav": en_nav } },
  'tr': { translation: { "errorBoundary": tr_errorBoundary, "nav": tr_nav } },
} as const;

export type EnTranslation = (typeof resources)['en']['translation'];
